######################################################################
##
## Filename: auto_choix_tb.udo
## Created on: Tue May 21 12:27:02 Paris, Madrid (heure d’été) 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
