######################################################################
##
## Filename: main_sch_main_sch_sch_tb.udo
## Created on: Tue Apr 16 09:21:44 Paris, Madrid (heure d’été) 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
