######################################################################
##
## Filename: main_sch_main_sch_sch_tb_un.udo
## Created on: Tue May 21 11:47:13 Paris, Madrid (heure d’été) 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
