######################################################################
##
## Filename: main_sch_main_sch_sch_tb_deux.udo
## Created on: Tue Apr 16 11:48:09 Paris, Madrid (heure d’été) 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
